function get_help_text(ht)   {

switch(ht)   {
case 1:
   helpText = "This HMAC key is generated by the First Data Global Gateway. First genrate on the gateway then copy and paste it here.";                      
   return helpText;  
break;
case 2:
   helpText = "This key id is listed on the First Data Global Gateway. Copy and paste it here.";                      
   return helpText;  
break;
case 3:
   helpText = "This Gateway id is listed on the First Data Global Gateway. Copy and paste it here.";                      
   return helpText;  
break;
case 4:
   helpText = "This password is generated by the First Data Global Gateway. First genrate on the gateway then copy and paste it here.";                      
   return helpText;  
break;
case 5:
   helpText = "The language you use for First Data. \"en\" is for english.";                      
   return helpText;  
break;
case 6:
   helpText = "This is the maximun number of times a rejected payment will be retried during the month.";                      
   return helpText;  
break;
case 7:
   helpText = "This is the maximun number of months we will continue to bill a client when billing constantly fails. When they reach this number of cycles they will be set to HOLD and sent to collections. A \"0\" value will turn this feature off.";                      
   return helpText;  
break;
case 8:
   helpText = "This is the link that is used for proccessing transactions. This link \"https://api.demo.globalgatewaye4.firstdata.com/transaction/v14/wsdl\" is for test transctions. This is for LIVE \"https://api.globalgatewaye4.firstdata.com/transaction/v14/wsdl\" DO NOT CHANGE THIS IF YOU ARE UNSURE BECAUSE NO PAYMENTS WILL ACTUALLY BE CHARGED TO THEIR CARDS. YET THE THEY WILL APEAR TO BE GOING THROUGH.";        
   return helpText;  
break;
case 9:
   helpText = "This is used to keep authorization charges down as they cost .10 cents each. Expired Cards are unbillable, howeveor if the card comes up expired and theis flag is set the entire billing cycle will be skipped for each particular card. So in certain instances this should be overidden if the cards are being updated so an entire billing cycle is not missed with those cards.";        
   return helpText;  
break;
case 10:
   helpText = "This is used to keep authorization charges down as they cost .10 cents each. NSF is the only bank flag that will go through upon resubmission, therefore flagging all other responses and stopping billing cuts down on authorization charges. In certain instances this should be overidden if the cards are being updated so an entire billing cycle is not missed with those cards.";        
   return helpText;  
break;
case 11:
   helpText = "This will send an email to the members on file email address when a payment fails the max amount of retries set above.";        
   return helpText;  
break;
case 12:
   helpText = "This is the Month that will be sent to the processor instead of this cards expired Month.";        
   return helpText;  
break;
case 13:
   helpText = "This is the Year that will be sent to the processor instead of this cards expired Year.";        
   return helpText;  
break;
}

}
